version: '3.3'
services:
  web:
    build:
      context: ./web
    tty: true
      #dockerfile: ruby/unicorn:latest
   # ports:
   #   - '80:80'
  app:
    build:
      context: ./app
      #dockerfile: web:latest
    #command: rails s -p 3000 -b '0.0.0.0'
    tty: true
    #command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb
   # ports:
   #   - '3000:3000'
  redis-master:
    build:
      context: ./redis-master
    restart: always
    tty: true
    privileged: true
    volumes: 
      - ./data/redis:/data
  redis-slave:
    build:
      context: ./redis-slave
    restart: always
    tty: true
    privileged: true
    volumes: 
      - ./data/redis:/data
  redis-sentinel-1:
    build: ./redis-sentinel-1
    restart: always
    tty: true
    privileged: true
    volumes: 
      - ./data/redis:/data
  
